### ISSUE TITLE
Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.deserialize

### ISSUE THREAD

**Issue by DexterSK** [Slimefun/Slimefun4#4084]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

`[15:59:36 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta for deserialization
java.lang.IllegalArgumentException: BlockStateTag({
    honey_level: "0"
}) is not a valid interface java.util.Map
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:241) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem.<init>(CraftMetaItem.java:547) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaBlockState.<init>(CraftMetaBlockState.java:164) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at jdk.internal.reflect.GeneratedConstructorAccessor266.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:205) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at jdk.internal.reflect.GeneratedMethodAccessor239.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.config.Config.<init>(Config.java:89) ~[Slimefun4 - DEV 1092 (git 16313).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.config.Config.<init>(Config.java:100) ~[Slimefun4 - DEV 1092 (git 16313).jar:?]
        at io.github.thebusybiscuit.slimefun4.api.player.PlayerProfile.<init>(PlayerProfile.java:82) ~[Slimefun4 - DEV 1092 (git 16313).jar:?]
        at io.github.thebusybiscuit.slimefun4.api.player.PlayerProfile.lambda$get$5(PlayerProfile.java:406) ~[Slimefun4 - DEV 1092 (git 16313).jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

### 📑 Reproduction Steps

not sure, sometimes appear in the console

### 💡 Expected Behavior

no error

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

[16:03:17 INFO]: This Server uses the following setup of Slimefun:
[16:03:17 INFO]: Purpur git-Purpur-2083 (MC: 1.20.2)
[16:03:17 INFO]: Slimefun DEV - 1104 (git c977454e)
[16:03:17 INFO]: Metrics-Module #29
[16:03:17 INFO]: Java 17
[16:03:17 INFO]: 
[16:03:17 INFO]: Installed Addons: (44)
[16:03:17 INFO]:   GlobalWarming vDEV - 11 (git 73ff77d4)
[16:03:17 INFO]:   Networks vDEV - 50 (git 3de3c9d6)
[16:03:17 INFO]:   ShopGUIPlus v1.81.1
[16:03:17 INFO]:   ExtraTools vDEV - 36 (git 922c0324)
[16:03:17 INFO]:   FoxyMachines vDEV - 67 (git 0028aa93)
[16:03:17 INFO]:   Quaptics vDEV - 4 (git cbc2e78e)
[16:03:17 INFO]:   SlimefunOreChunks vDEV - 15 (git 2520cb23)
[16:03:17 INFO]:   FNAmplifications vDev - 99
[16:03:17 INFO]:   Bump vBuild 32 zh-CN(SlimefunGuguProject) (git 4923d02)
[16:03:17 INFO]:   DynaTech v1.0.0
[16:03:17 INFO]:   CreativeManager v1.31.4
[16:03:17 INFO]:   AdvancedEnchantments v9.5.5
[16:03:17 INFO]:   ExtraGear vDEV - 13 (git c62047e2)
[16:03:17 INFO]:   SlimeHUD vDEV - 11 (git b6dc2d53)
[16:03:17 INFO]:   InfinityExpansion vDEV - 144 (git 9da37202)
[16:03:17 INFO]:   Supreme vDEV - 29 (git f9e70053)
[16:03:17 INFO]:   SFCalc vDEV - 37 (git dfc0fc41)
[16:03:17 INFO]:   Wildernether vDEV - 5 (git 5be3da69)
[16:03:17 INFO]:   CompressionCraft vDEV - 25 (git dbca94b8)
[16:03:17 INFO]:   UltimateGenerators v1.0.8
[16:03:17 INFO]:   ExtraHeads vDEV - 25 (git 8c29f73a)
[16:03:17 INFO]:   SlimyTreeTaps vDEV - 20 (git 963f0383)
[16:03:17 INFO]:   FlowerPower vDEV - 16 (git 5a38d1c6)
[16:03:17 INFO]:   TranscEndence vDEV - 41 (git 98d7d47e)
[16:03:17 INFO]:   CMI v9.6.9.5
[16:03:17 INFO]:   FluffyMachines vDEV - 132 (git ccf029ba)
[16:03:17 INFO]:   GeneticChickengineering v1.0
[16:03:17 INFO]:   ItemsAdder v3.6.3-beta-6
[16:03:17 INFO]:   Brewery v3.1.1
[16:03:17 INFO]:   Nexcavate v1.0
[16:03:17 INFO]:   DyedBackpacks vDEV - 17 (git 8b329e96)
[16:03:17 INFO]:   AdvancedChests v27.8
[16:03:17 INFO]:   Residence v5.1.4.1
[16:03:17 INFO]:   EcoPower vDEV - 5 (git 5c1ecd68)
[16:03:17 INFO]:   SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
[16:03:17 INFO]:   ExoticGarden vDEV - 78 (git 7f9a5f63)
[16:03:17 INFO]:   HeadLimiter vDEV - 14 (git 0a02e2fd)
[16:03:17 INFO]:   DankTech2 vDEV - 9 (git aa6c2209)
[16:03:17 INFO]:   Liquid vDEV - 14 (git 0f5346bf)
[16:03:17 INFO]:   LiteXpansion vDEV 189 (git b2d7c)
[16:03:17 INFO]:   SimpleUtils vDEV - 15 (git 4250fd5e)
[16:03:17 INFO]:   ElementManipulation vDEV - 28 (git 2b469991)
[16:03:17 INFO]:   TinkerTools v2.1.0
[16:03:17 INFO]:   ChocoHills v1.0

**Comment by Boomer-1** [comment]
you need to update to the latest version of slimefun.

**Comment by Boomer-1** [comment]
https://blob.build/project/Slimefun4/Dev you can download it here

**Comment by DexterSK** [comment]
> https://blob.build/project/Slimefun4/Dev you can download it here

oh thanks
